name: Simple GitHub Action

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependency
        run : npm i

      - name: run lint
        run : npm run lint

  deploy:
    needs: jobs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: install dependency
        run : npm i

      - name: build project
        run : npm run build

      - name: serve project
        run : echo "App Running on port 3000"